---
name: Build and Push Node Image to Google Cloud Platform.
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr-1:
    name: Build and Push saveStat to GCP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'saveStat'
        runtime: 'nodejs16'

  build-push-gcr-2:
    name: Build and Push cleanRoomSession to GCP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'cleanRoomSession'
        runtime: 'nodejs16'
